### ISSUE TITLE
gnuplot is an undocumented dependency of poreTally

### ISSUE THREAD

**Issue by SamStudio8** [cvdelannoy/poreTally#3]
My instance of `poreTally` aborted while trying to run `Canu` as it first checks for the availability of `gnuplot` - which I didn't have installed. You might want to add this to your `setup.py` (or the `assembler_commands/canu.yaml`?).

**Comment by cvdelannoy** [comment]
Hi, thanks for letting me know! That's odd because this should really be handled by conda. I tried it in a clean container, conda automatically picked up on the absence of gnuplot and installed it in the environment. Added it as an explicit depencency in canu.yaml to be absolutely sure, can't hurt anyway.

**Comment by SamStudio8** [comment]
Strange... Perhaps this was something wrong with my environment. Thanks for
investigating!
